steps:
  # pull the previous docker image to utilize the cache
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - 'docker pull gcr.io/$PROJECT_ID/newsletter:latest || exit 0' # exit 0 to ignore errors, if we are running the build for the first time
  # build the image with latest code
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/newsletter:latest'
  - '-f'
  - './Dockerfile'
  - '--cache-from'
  - 'gcr.io/$PROJECT_ID/newsletter:latest'
  - '.'
  timeout: 3600s
  # push the updated image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/newsletter:latest']
  # deploy the service with latest image
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'newsletter'
  - '--image'
  - 'gcr.io/$PROJECT_ID/newsletter:latest'
  - '--region'
  - 'us-central1'
  - '--allow-unauthenticated'
  - '--memory'
  - '1Gi'
  - '--cpu'
  - '1'
  - '--max-instances'
  - '1'

options:
  machineType: 'E2_HIGHCPU_8'
